import type { Lang } from "@/lib/i18n";

export type PowerRound = {
  question: string;
  left: { label: string; detail: string };
  right: { label: string; detail: string };
  correct: "left" | "right";
  fact: string;
};

const PL_ROUNDS: PowerRound[] = [
  {
    question: "Co oszczędza więcej energii rocznie?",
    left: { label: "Żarówka LED 9 W", detail: "~11 kWh/rok" },
    right: { label: "Żarówka klasyczna 60 W", detail: "~70 kWh/rok" },
    correct: "left",
    fact: "LED zużywa nawet 6× mniej prądu przy tym samym strumieniu świetlnym.",
  },
  {
    question: "Która pralka jest efektywniejsza?",
    left: { label: "Klasa A", detail: "~180 kWh/rok" },
    right: { label: "Klasa F", detail: "~410 kWh/rok" },
    correct: "left",
    fact: "Nowa skala UE A–G jest surowsza. Dzisiejsza A ≈ połowa zużycia F.",
  },
  {
    question: "Co bardziej obniża rachunek za ogrzewanie?",
    left: { label: "Głowice termostatyczne", detail: "−15 % rocznie" },
    right: { label: "Zamknięte drzwi do pokoju", detail: "marginalnie" },
    correct: "left",
    fact: "Termostaty wyłączają grzejnik po osiągnięciu temperatury — typowo 10–15 % oszczędności rocznie.",
  },
  {
    question: "Które urządzenie ma większe zużycie?",
    left: { label: "Suszarka 1 h", detail: "~2.5 kWh" },
    right: { label: "Laptop 8 h", detail: "~0.5 kWh" },
    correct: "left",
    fact: "Suszarka to jeden z największych pożeraczy prądu. Suszenie na powietrzu jest darmowe.",
  },
  {
    question: "Co bardziej oszczędza w kuchni?",
    left: { label: "Pokrywka na garnku", detail: "−30 % energii" },
    right: { label: "Gotowanie bez pokrywki", detail: "baza" },
    correct: "left",
    fact: "Pokrywka trzyma ciepło — szybsze gotowanie, mniejsze zużycie.",
  },
  {
    question: "Które urządzenie ma mniejszy pobór w stanie czuwania?",
    left: { label: "TV w standby", detail: "~0.5 W" },
    right: { label: "Stary dekoder", detail: "~15 W" },
    correct: "left",
    fact: "Standby ciągnie 24/7. 15 W × 8760 h = 131 kWh/rok na nic.",
  },
  {
    question: "Co taniej podgrzewa wodę w Polsce?",
    left: { label: "Piec gazowy", detail: "~6 kWh eq./dzień" },
    right: { label: "Bojler elektryczny", detail: "~8 kWh/dzień" },
    correct: "left",
    fact: "Gaz w Polsce jest nadal tańszy do podgrzewania wody niż energia elektryczna z miksu.",
  },
  {
    question: "Co bardziej obniży rachunek za światło?",
    left: { label: "Wyłączyć światło w nieużywanym pokoju", detail: "−5–10 %" },
    right: { label: "Zostawić dla bezpieczeństwa", detail: "zbędne kWh" },
    correct: "left",
    fact: "Każda żarówka 9 W × 10 h × 365 dni = ~33 kWh/rok na pokój.",
  },
  {
    question: "Lepszy zakup długoterminowo?",
    left: { label: "Lodówka A+++ za 2500 zł", detail: "~140 kWh/rok" },
    right: { label: "Lodówka A+ za 1500 zł", detail: "~290 kWh/rok" },
    correct: "left",
    fact: "Różnica 150 kWh/rok × ~0.90 zł ≈ 135 zł rocznie. Zwrot ~7 lat, a lodówka działa 15+.",
  },
  {
    question: "Co zmniejsza rachunek za ogrzewanie?",
    left: { label: "Uszczelnione okna", detail: "−10 do 15 % ciepła" },
    right: { label: "Otwarte okno przy włączonym grzejniku", detail: "strata" },
    correct: "left",
    fact: "Ogrzewanie przez otwarte okno = pieniądze ulatujące. Krótkie intensywne wietrzenie jest lepsze.",
  },
  {
    question: "Które źródło jest odnawialne?",
    left: { label: "Fotowoltaika", detail: "słońce" },
    right: { label: "Gaz ziemny", detail: "paliwo kopalne" },
    correct: "left",
    fact: "Słońce, wiatr, woda, biomasa, geotermia = OZE. Węgiel, ropa, gaz = kopalne.",
  },
  {
    question: "Co droższe w eksploatacji miesięcznie?",
    left: { label: "Klimatyzacja 8 h/dzień", detail: "~60 kWh/mies" },
    right: { label: "Wentylator 8 h/dzień", detail: "~12 kWh/mies" },
    correct: "left",
    fact: "Klimatyzacja zużywa rzędami wielkości więcej. Wentylator lub zacienienie oszczędzają sporo latem.",
  },
  {
    question: "Co lepsze dla rachunku za wodę?",
    left: { label: "Prysznic 5 min", detail: "~50 l" },
    right: { label: "Kąpiel w wannie", detail: "~150 l" },
    correct: "left",
    fact: "Prysznic zużywa ~3× mniej wody niż pełna wanna.",
  },
  {
    question: "Które źródło emituje najmniej CO₂?",
    left: { label: "Elektrownia jądrowa", detail: "~12 g CO₂/kWh" },
    right: { label: "Elektrownia węglowa", detail: "~900 g CO₂/kWh" },
    correct: "left",
    fact: "Atom = niskie emisje porównywalne z OZE. Węgiel to lider emisyjny.",
  },
  {
    question: "Co długoterminowo obniża koszty?",
    left: { label: "Inwestycja w ocieplenie", detail: "−20–40 % na ogrzewanie" },
    right: { label: "Wyższa temperatura termostatu", detail: "+7 % za każdy °C" },
    correct: "left",
    fact: "Każdy °C wyżej na termostacie = ~7 % wyższy rachunek. Izolacja zwraca się wolno, ale istotnie.",
  },
  {
    question: "Co bardziej opłacalne dla kieszeni młodej osoby?",
    left: { label: "ETF MSCI World co miesiąc 100 zł", detail: "średnio ~7 % r/r" },
    right: { label: "Konto oszczędnościowe 2 %", detail: "poniżej inflacji" },
    correct: "left",
    fact: "Przy horyzoncie 20+ lat ETF zwykle bije lokaty i konta oszczędnościowe. Ale pamiętaj — ETF ma zmienność.",
  },
  {
    question: "Co chroni przed inflacją?",
    left: { label: "Obligacje indeksowane inflacją (EDO)", detail: "kupon = inflacja + marża" },
    right: { label: "Gotówka w szufladzie", detail: "realnie traci" },
    correct: "left",
    fact: "EDO/ROD w PL są indeksowane inflacją. Gotówka przy inflacji 10 % traci 10 % siły nabywczej rocznie.",
  },
  {
    question: "Co tańsze dla rachunku miesięcznego?",
    left: { label: "Transport publiczny (ZTM miesięczny)", detail: "~150 zł/mies" },
    right: { label: "Własne auto do pracy", detail: "~800–1500 zł/mies" },
    correct: "left",
    fact: "Auto = paliwo + parking + serwis + ubezpieczenie + utrata wartości. W mieście ZTM jest taniej i szybciej.",
  },
];

const UK_ROUNDS: PowerRound[] = [
  {
    question: "Що економить більше енергії за рік?",
    left: { label: "LED-лампа 9 Вт", detail: "~11 кВт·год/рік" },
    right: { label: "Класична 60 Вт", detail: "~70 кВт·год/рік" },
    correct: "left",
    fact: "LED споживає до 6× менше електрики за того самого світлового потоку.",
  },
  {
    question: "Яка пральна машина ефективніша?",
    left: { label: "Клас енергоефективності A", detail: "~180 кВт·год/рік" },
    right: { label: "Клас F", detail: "~410 кВт·год/рік" },
    correct: "left",
    fact: "Нова шкала ЄС A–G суворіша. Сучасний клас A — приблизно вдвічі менше ніж F.",
  },
  {
    question: "Який прилад споживає більше?",
    left: { label: "Сушарка 1 год", detail: "~2.5 кВт·год" },
    right: { label: "Ноутбук 8 год", detail: "~0.5 кВт·год" },
    correct: "left",
    fact: "Сушарка — один з найбільших «з'їдачів» енергії. Сушіння на повітрі — безкоштовне.",
  },
  {
    question: "Що зменшує рахунок за опалення?",
    left: { label: "Термоголовки на радіаторах", detail: "−15 % на рік" },
    right: { label: "Зачинені двері до кімнати", detail: "незначно" },
    correct: "left",
    fact: "Термоголовки вимикають радіатор при досягненні заданої температури — зазвичай 10–15 % економії.",
  },
  {
    question: "Кришка на каструлі при варінні...",
    left: { label: "Так, є", detail: "−30 % енергії" },
    right: { label: "Без кришки", detail: "базове споживання" },
    correct: "left",
    fact: "Кришка тримає тепло — швидше готування, менше електрики/газу.",
  },
  {
    question: "Який прилад має менше споживання в режимі очікування?",
    left: { label: "Сучасний ТВ standby", detail: "~0.5 Вт" },
    right: { label: "Старий ресивер", detail: "~15 Вт" },
    correct: "left",
    fact: "Standby йде 24/7. 15 Вт × 8760 год = 131 кВт·год на рік даремно.",
  },
  {
    question: "Що краще для рахунку за світло?",
    left: { label: "Вимкнути світло в порожній кімнаті", detail: "−5–10 %" },
    right: { label: `Залишати «про всяк випадок»`, detail: "зайві кВт·год" },
    correct: "left",
    fact: "Проста звичка вимикати світло економить помітні гроші — особливо з українськими тарифами.",
  },
  {
    question: "Довгостроково вигідніша покупка?",
    left: { label: "Інверторний холодильник A+++", detail: "~140 кВт·год/рік" },
    right: { label: "Старий A+ холодильник", detail: "~290 кВт·год/рік" },
    correct: "left",
    fact: "Різниця ~150 кВт·год × ~4 грн = ~600 грн/рік. Холодильник працює 15+ років.",
  },
  {
    question: "Що знижує теплові втрати?",
    left: { label: "Ущільнення вікон", detail: "−10 до 15 % тепла" },
    right: { label: "Відкрите вікно при опаленні", detail: "прямі втрати" },
    correct: "left",
    fact: "Краще коротке інтенсивне провітрювання (5 хв) ніж постійно відкрите вікно.",
  },
  {
    question: "Яке джерело відновлюване?",
    left: { label: "Сонячна електростанція", detail: "сонце" },
    right: { label: "Газова котельня", detail: "фосильне пальне" },
    correct: "left",
    fact: "Сонце, вітер, вода, біомаса, геотермальна = ВДЕ. Вугілля, нафта, газ = фосильні.",
  },
  {
    question: "Що дорожче щомісяця?",
    left: { label: "Кондиціонер 8 год/день", detail: "~60 кВт·год/міс" },
    right: { label: "Вентилятор 8 год/день", detail: "~12 кВт·год/міс" },
    correct: "left",
    fact: "Кондиціонер споживає в 5× більше. Вентилятор + затемнення влітку дешевше.",
  },
  {
    question: "Що краще для рахунку за воду?",
    left: { label: "Душ 5 хв", detail: "~50 л" },
    right: { label: "Ванна", detail: "~150 л" },
    correct: "left",
    fact: "Душ споживає ~3× менше води ніж повна ванна.",
  },
  {
    question: "Яке джерело має найменші викиди CO₂?",
    left: { label: "АЕС (ЗАЕС, ЮУАЕС тощо)", detail: "~12 г CO₂/кВт·год" },
    right: { label: "Вугільна ТЕС", detail: "~900 г CO₂/кВт·год" },
    correct: "left",
    fact: "Атом має низькі викиди, порівняні з ВДЕ. Вугілля — лідер за викидами.",
  },
  {
    question: "Довгостроково знижує витрати на опалення?",
    left: { label: "Утеплення будинку", detail: "−20–40 % на опалення" },
    right: { label: "Вища температура термостата", detail: "+7 % за кожен °C" },
    correct: "left",
    fact: "Кожен +1 °C = ~7 % вище рахунок. Утеплення окупається повільно, але суттєво.",
  },
  {
    question: "Що вигідніше для молодої людини довгостроково?",
    left: { label: "ETF + ОВДП щомісяця", detail: "~7–14 % річних" },
    right: { label: "Готівка в доларах у шафі", detail: "інфляція USD + ризики" },
    correct: "left",
    fact: "Навіть в умовах нестабільності: частина коштів у ліквідних активах (ОВДП, ETF) росте.",
  },
  {
    question: "Що захищає від інфляції гривні?",
    left: { label: "Валютні ОВДП або ETF", detail: "хедж проти курсу" },
    right: { label: "Готівка в гривні під подушкою", detail: "реально знецінюється" },
    correct: "left",
    fact: "Валютні ОВДП або MSCI World ETF хеджують від інфляції та девальвації одночасно.",
  },
  {
    question: "Дешевший у перспективі транспорт?",
    left: { label: "Громадський транспорт у Києві", detail: "~1200 грн/міс" },
    right: { label: "Власне авто щодня", detail: "~10000+ грн/міс" },
    correct: "left",
    fact: "Авто = пальне + страховка + ТО + парковка + амортизація. У місті авто часто неефективне.",
  },
];

const CS_ROUNDS: PowerRound[] = [
  {
    question: "Co ušetří více energie ročně?",
    left: { label: "LED 9 W", detail: "~11 kWh/rok" },
    right: { label: "Klasická 60 W", detail: "~70 kWh/rok" },
    correct: "left",
    fact: "LED spotřebuje až 6× méně elektřiny při stejném světelném výkonu.",
  },
  {
    question: "Která pračka je efektivnější?",
    left: { label: "Třída A", detail: "~180 kWh/rok" },
    right: { label: "Třída F", detail: "~410 kWh/rok" },
    correct: "left",
    fact: "Nová škála A–G v EU je přísnější. Dnešní A ≈ polovina spotřeby F.",
  },
  {
    question: "Co víc sníží účet za vytápění?",
    left: { label: "Termostatické hlavice", detail: "−15 % ročně" },
    right: { label: "Zavřené dveře do pokoje", detail: "marginálně" },
    correct: "left",
    fact: "Termostatické hlavice vypnou radiátor při dosažení teploty — typicky 10–15 % úspora.",
  },
  {
    question: "Která spotřeba je větší?",
    left: { label: "Sušička 1 h", detail: "~2.5 kWh" },
    right: { label: "Notebook 8 h", detail: "~0.5 kWh" },
    correct: "left",
    fact: "Sušička je jeden z největších žroutů. Sušení na vzduchu je zadarmo.",
  },
  {
    question: "Co víc ušetří v kuchyni?",
    left: { label: "Poklička na hrnci", detail: "−30 % energie" },
    right: { label: "Vaření bez pokličky", detail: "referenční" },
    correct: "left",
    fact: "Poklička drží teplo — rychlejší vaření, menší spotřeba.",
  },
  {
    question: "Který spotřebič má menší standby spotřebu?",
    left: { label: "TV ve standby", detail: "~0.5 W" },
    right: { label: "Starý set-top-box", detail: "~15 W" },
    correct: "left",
    fact: "Standby jede 24/7. 15 W × 8760 h = 131 kWh/rok zbytečně.",
  },
  {
    question: "Co v ČR levněji ohřeje vodu?",
    left: { label: "Plynový ohřívač", detail: "~6 kWh ekv./den" },
    right: { label: "Elektrický bojler", detail: "~8 kWh/den" },
    correct: "left",
    fact: "Plyn byl v ČR dlouho levnější na ohřev vody. Srovnej si aktuální ceny u svého dodavatele.",
  },
  {
    question: "Co víc sníží účet za osvětlení?",
    left: { label: "Vypnout světlo v nepoužívané místnosti", detail: "−5–10 %" },
    right: { label: `Nechat „pro jistotu"`, detail: "zbytečné kWh" },
    correct: "left",
    fact: "Každá 9 W žárovka × 10 h × 365 dní = ~33 kWh/rok na místnost.",
  },
  {
    question: "Lepší nákup dlouhodobě?",
    left: { label: "A+++ lednice za 15 000 Kč", detail: "~140 kWh/rok" },
    right: { label: "A+ lednice za 9 000 Kč", detail: "~290 kWh/rok" },
    correct: "left",
    fact: "Rozdíl 150 kWh × ~6 Kč = ~900 Kč/rok. Lednice drží 15+ let.",
  },
  {
    question: "Co sníží ztráty tepla?",
    left: { label: "Utěsněná okna", detail: "−10 až 15 % tepla" },
    right: { label: "Otevřené okno při topení", detail: "přímá ztráta" },
    correct: "left",
    fact: "Vytápění při otevřeném okně = peníze letí ven. Lepší je krátké intenzivní větrání.",
  },
  {
    question: "Který zdroj je obnovitelný?",
    left: { label: "Fotovoltaika", detail: "slunce" },
    right: { label: "Zemní plyn", detail: "fosilní" },
    correct: "left",
    fact: "Slunce, vítr, voda, biomasa, geotermální = OZE. Uhlí, ropa, plyn = fosilní.",
  },
  {
    question: "Co dražší měsíčně?",
    left: { label: "Klimatizace 8 h/den", detail: "~60 kWh/měs" },
    right: { label: "Ventilátor 8 h/den", detail: "~12 kWh/měs" },
    correct: "left",
    fact: "Klimatizace spotřebuje řádově víc. V létě pomáhá ventilátor + stínění.",
  },
  {
    question: "Co lepší pro účet za vodu?",
    left: { label: "Sprcha 5 min", detail: "~50 l" },
    right: { label: "Vana", detail: "~150 l" },
    correct: "left",
    fact: "Sprcha spotřebuje ~3× méně vody než plná vana.",
  },
  {
    question: "Který zdroj má nejmenší emise CO₂?",
    left: { label: "Jaderná elektrárna (Temelín, Dukovany)", detail: "~12 g CO₂/kWh" },
    right: { label: "Uhelná elektrárna", detail: "~900 g CO₂/kWh" },
    correct: "left",
    fact: "Jádro má nízké emise srovnatelné s OZE. ČR plánuje novou JE — Dukovany 5.",
  },
  {
    question: "Co dlouhodobě sníží náklady?",
    left: { label: "Zateplení domu", detail: "−20–40 % na topení" },
    right: { label: "Vyšší teplota termostatu", detail: "+7 % za každý °C" },
    correct: "left",
    fact: "Každý °C nahoru = ~7 % vyšší účet. Zateplení má návratnost 10+ let, ale významnou úsporu.",
  },
  {
    question: "Dlouhodobě výhodnější pro mladého Čecha?",
    left: { label: "Pravidelný nákup ETF MSCI World", detail: "~7 % r/r historicky" },
    right: { label: "Spořicí účet s 2 % úrokem", detail: "pod inflací" },
    correct: "left",
    fact: "Při horizontu 20+ let ETF zpravidla bije spoření. Po 3 letech je výnos v ČR bez daně.",
  },
  {
    question: "Co chrání před inflací?",
    left: { label: "Reprofondy / reálná aktiva", detail: "navázané na ekonomiku" },
    right: { label: "Hotovost v peněžence", detail: "reálně ztrácí" },
    correct: "left",
    fact: "Při inflaci 10 % ztrácí hotovost 10 % síly. Akciový trh historicky poráží inflaci v dlouhém období.",
  },
  {
    question: "Co levnější v Praze dlouhodobě?",
    left: { label: "Litačka + tramvaj", detail: "~365 Kč/měs" },
    right: { label: "Vlastní auto do práce", detail: "~8000 Kč+/měs" },
    correct: "left",
    fact: "Auto = palivo + pojištění + parkování + servis + amortizace. V Praze MHD poráží auto na čase i penězích.",
  },
];

const EN_ROUNDS: PowerRound[] = [
  {
    question: "Which saves more energy yearly?",
    left: { label: "LED 9 W bulb", detail: "~11 kWh/year" },
    right: { label: "Classic 60 W bulb", detail: "~70 kWh/year" },
    correct: "left",
    fact: "LED uses up to 6× less electricity at the same light output.",
  },
  {
    question: "Which washing machine is more efficient?",
    left: { label: "Energy class A", detail: "~180 kWh/year" },
    right: { label: "Energy class F", detail: "~410 kWh/year" },
    correct: "left",
    fact: "The new EU A–G scale is stricter. Today's A ≈ half the consumption of F.",
  },
  {
    question: "Which device uses more energy?",
    left: { label: "Clothes dryer 1 h", detail: "~2.5 kWh" },
    right: { label: "Laptop 8 h", detail: "~0.5 kWh" },
    correct: "left",
    fact: "Dryers are among the worst energy hogs. Air-drying is free.",
  },
  {
    question: "What lowers heating bills more?",
    left: { label: "Thermostatic radiator valves", detail: "−15 % yearly" },
    right: { label: "Closing room doors", detail: "marginal" },
    correct: "left",
    fact: "Valves cut off the radiator once the target temp is reached — typically 10–15 % savings.",
  },
  {
    question: "What saves more in the kitchen?",
    left: { label: "Lid on the pot", detail: "−30 % energy" },
    right: { label: "Cooking without lid", detail: "baseline" },
    correct: "left",
    fact: "A lid traps heat — faster cooking, lower consumption.",
  },
  {
    question: "Which device has less standby draw?",
    left: { label: "Modern TV standby", detail: "~0.5 W" },
    right: { label: "Old set-top box", detail: "~15 W" },
    correct: "left",
    fact: "Standby runs 24/7. 15 W × 8760 h = 131 kWh/year wasted.",
  },
  {
    question: "What's better for your water bill?",
    left: { label: "5-minute shower", detail: "~50 L" },
    right: { label: "Full bathtub", detail: "~150 L" },
    correct: "left",
    fact: "A shower uses ~3× less water than a full bath.",
  },
  {
    question: "Which emits less CO₂?",
    left: { label: "Nuclear power plant", detail: "~12 g CO₂/kWh" },
    right: { label: "Coal power plant", detail: "~900 g CO₂/kWh" },
    correct: "left",
    fact: "Nuclear has emissions comparable to renewables. Coal is the top emitter.",
  },
  {
    question: "Which is renewable energy?",
    left: { label: "Solar PV", detail: "sun" },
    right: { label: "Natural gas", detail: "fossil fuel" },
    correct: "left",
    fact: "Sun, wind, water, biomass, geothermal = renewable. Coal, oil, gas = fossil.",
  },
  {
    question: "Which is more expensive monthly?",
    left: { label: "AC 8 h/day", detail: "~60 kWh/mo" },
    right: { label: "Fan 8 h/day", detail: "~12 kWh/mo" },
    correct: "left",
    fact: "AC uses an order of magnitude more. A fan + shading wins in most summers.",
  },
  {
    question: "Long-term investment for a young saver?",
    left: { label: "MSCI World ETF, monthly DCA", detail: "~7 % historic return" },
    right: { label: "Savings account at 2 %", detail: "below inflation" },
    correct: "left",
    fact: "Over 20+ years, index ETFs tend to beat savings. But they can drop −40 % in bear markets.",
  },
  {
    question: "What protects against inflation?",
    left: { label: "Inflation-linked bonds + equities", detail: "real assets" },
    right: { label: "Cash in a drawer", detail: "loses value" },
    correct: "left",
    fact: "With 4 % inflation, €1000 cash loses €40/year in real terms.",
  },
  {
    question: "What saves thousands over time?",
    left: { label: "Home insulation upgrade", detail: "−20–40 % heating" },
    right: { label: "Turning up the thermostat", detail: "+7 % per °C" },
    correct: "left",
    fact: "Every +1 °C on the thermostat = ~7 % higher bill. Insulation has long but significant ROI.",
  },
  {
    question: "Which transport saves most in a city?",
    left: { label: "Public transit monthly pass", detail: "~€30–80/mo" },
    right: { label: "Owning a car", detail: "~€400–800/mo all-in" },
    correct: "left",
    fact: "Car costs: fuel + insurance + parking + maintenance + depreciation. In cities, transit usually wins.",
  },
  {
    question: "Better for long-term wealth?",
    left: { label: "Pay off 18 % APR credit card", detail: "guaranteed 18 % return" },
    right: { label: "Invest in S&P 500 while carrying balance", detail: "~7 % avg" },
    correct: "left",
    fact: "Paying off high-interest debt is a guaranteed return equal to the APR. Beat the market, risk-free.",
  },
  {
    question: "Which has cheaper operating cost per km?",
    left: { label: "Electric car (domestic tariff)", detail: "~€1.5 / 100 km" },
    right: { label: "Petrol car", detail: "~€8 / 100 km" },
    correct: "left",
    fact: "At home-charging rates, EVs are 4–5× cheaper per km. Upfront cost is higher, but ROI ~5 years.",
  },
];

const POOLS: Record<Lang, PowerRound[]> = {
  pl: PL_ROUNDS,
  uk: UK_ROUNDS,
  cs: CS_ROUNDS,
  en: EN_ROUNDS,
};

export function powerRoundsFor(lang: Lang): PowerRound[] {
  return POOLS[lang];
}

export const POWER_ROUNDS = PL_ROUNDS;
export const DURATION_SECONDS = 30;
export const XP_CORRECT = 10;
export const XP_WRONG = 5;
export const XP_CAP = 180;
