/* Per-market theme pools + landmark overlays — Phase 9.1 + 9.2.
 *
 * Each market has its own research-seed pool rooted in that country's
 * financial + energy context. The PL pool lives in `research.ts`
 * (legacy). CZ + UA pools live here so adding a market doesn't require
 * touching the primary research file.
 *
 * Landmark overlays (9.1.3 + 9.2 equivalent): a per-market catalogue of
 * iconic buildings + their slot categories, consumed by a future
 * landmark-aware CityScene. MVP ships the data + types; the UI swap is
 * a Phase 9 follow-up.
 */

import type { ResearchSeed } from "./research";

// ---------------------------------------------------------------------------
// CZ market — 20 themes
// ---------------------------------------------------------------------------

export const CZ_THEMES: Omit<ResearchSeed, "difficulty">[] = [
  {
    theme: "ČNB repo sazba — jak ovlivňuje hypotéky",
    kind: "quiz",
    buildingName: "ČNB Watch",
    buildingGlyph: "🏛️",
    buildingRoof: "bg-rose-400",
    buildingBody: "bg-rose-600",
    source: "ČNB + česká bankovnictví",
    notes: "Jak ČNB repo sazba ovlivňuje hypotéky, úroky z vkladů, inflaci.",
    angles: [
      "repo sazba vs hypotéční úrok — jaký je vztah",
      "úroky z běžných účtů vs inflace 2026",
      "repo 7 % vs 3 % — dopad na rodinný rozpočet",
      "mimořádné zasedání ČNB — kdy se svolává",
    ],
    age: "13-15",
    subject: "credit",
  },
  {
    theme: "ČSOB vs KB vs MONETA — bankovní účty v ČR",
    kind: "match-pairs",
    buildingName: "Banka",
    buildingGlyph: "🏦",
    buildingRoof: "bg-sky-400",
    buildingBody: "bg-sky-700",
    source: "Česká bankovní asociace",
    notes: "Spáruj banku s její klíčovou službou (produktem).",
    angles: [
      "mobilní apky: Smart banka / George / MONETA Smart",
      "business banking: KB KB+ / ČSOB korporátní / MONETA Firmy",
      "hypotéky: fixace 3Y / 5Y / 10Y u různých bank",
      "studentské účty do 26 let",
    ],
    age: "16-19",
    subject: "payments",
  },
  {
    theme: "DPH v ČR — 21 %, 15 %, 10 %",
    kind: "quiz",
    buildingName: "Finanční úřad",
    buildingGlyph: "📜",
    buildingRoof: "bg-zinc-400",
    buildingBody: "bg-zinc-600",
    source: "MF ČR + zákon o DPH",
    notes: "Základní / snížená / druhá snížená sazba — na co se která vztahuje.",
    angles: [
      "knihy, léky, potraviny — která sazba",
      "restaurace vs food-delivery — rozdíl",
      "DPH při koupi auta nového vs ojetého",
      "osvobození od DPH pro malé podnikatele",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "Daně z příjmu fyzických osob ČR",
    kind: "fill-in-blank",
    buildingName: "Daně",
    buildingGlyph: "🧾",
    buildingRoof: "bg-amber-400",
    buildingBody: "bg-amber-700",
    source: "MF ČR",
    notes: "Progresivní daň (15 % / 23 %), solidární příplatek, slevy na poplatníka.",
    angles: [
      "sleva na poplatníka 2026 — kolik korun",
      "hranice 15 % vs 23 % sazba",
      "zaměstnanec vs OSVČ — výpočet čistého",
      "daňový bonus na dítě",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "První byt v Praze — nájem vs hypotéka",
    kind: "what-if",
    buildingName: "První M",
    buildingGlyph: "🗝️",
    buildingRoof: "bg-fuchsia-400",
    buildingBody: "bg-fuchsia-600",
    source: "Hypoteční trh ČR 2026",
    notes: "25 mil vs 18 000 Kč nájem — kdy se vyplatí co.",
    angles: [
      "pronájem 2+kk Praha 4 vs hypotéka 5 mil. na 30 let",
      "akontace 10 % vs 20 % — rozdíl v úroku",
      "fixace 5Y vs 10Y vs variabilní",
      "refinancování po 5 letech",
    ],
    age: "16-19",
    subject: "realestate",
  },
  {
    theme: "Penzijní spoření a DPS v ČR",
    kind: "quiz",
    buildingName: "Penze Hub",
    buildingGlyph: "👴",
    buildingRoof: "bg-violet-400",
    buildingBody: "bg-violet-600",
    source: "Ministerstvo financí + penzijní společnosti",
    notes: "DPS / DIP limits, státní příspěvek, daňová úleva.",
    angles: [
      "maximální státní příspěvek 2026",
      "DPS vs DIP — rozdíl",
      "daňová úleva až 48 000 Kč",
      "výběr po 60. roce",
    ],
    age: "16-19",
    subject: "investing",
  },
  {
    theme: "Česká pošta a bankovní identita",
    kind: "true-false",
    buildingName: "Pošta",
    buildingGlyph: "📮",
    buildingRoof: "bg-red-400",
    buildingBody: "bg-red-600",
    source: "Česká pošta + MojeID",
    notes: "Bankovní identita (BankID), MojeID, datová schránka.",
    angles: [
      "BankID funguje v bankách státní správy",
      "Datová schránka — kdy povinná",
      "MojeID vs BankID — rozdíl",
      "elektronický podpis v ČR",
    ],
    age: "16-19",
    subject: "everyday",
  },
  {
    theme: "Akcie na BCPP (Burza Praha)",
    kind: "scramble",
    buildingName: "BCPP",
    buildingGlyph: "📈",
    buildingRoof: "bg-yellow-400",
    buildingBody: "bg-yellow-700",
    source: "Burza cenných papírů Praha",
    notes: "Klíčové burzovní pojmy v češtině.",
    angles: [
      "AKCIE, DIVIDENDY, INDEX",
      "KURZ, VÝNOS, KAPITALIZACE",
      "BUŘE, MEDVĚD, KOREKCE",
      "FUTURES, OPCE, DERIVÁT",
    ],
    age: "16-19",
    subject: "investing",
  },
  {
    theme: "ČEZ a energetika — koruny za kWh",
    kind: "price-guess",
    buildingName: "ČEZ Hub",
    buildingGlyph: "⚡",
    buildingRoof: "bg-emerald-400",
    buildingBody: "bg-emerald-700",
    source: "ČEZ + ERÚ",
    notes: "Ceny elektřiny, distribuce, regulace.",
    angles: [
      "cena 1 kWh pro domácnost ČR 2026",
      "roční spotřeba bytu 3+1",
      "noční tarif D26 — rozdíl",
      "fotovoltaika náklady 5 kWp",
    ],
    age: "13-15",
    subject: "energy",
  },
  {
    theme: "Stavební spořitelna ČR",
    kind: "quiz",
    buildingName: "Stavební",
    buildingGlyph: "🏠",
    buildingRoof: "bg-orange-400",
    buildingBody: "bg-orange-600",
    source: "Českomoravská stavební spořitelna + další",
    notes: "Stavební spoření, státní podpora, úrok.",
    angles: [
      "maximální státní podpora 2026",
      "vázací doba 6 let",
      "úvěr ze stavebního spoření",
      "stavební spoření vs hypotéka",
    ],
    age: "16-19",
    subject: "savings",
  },
  {
    theme: "Kieszonkovné a spoření pro děti v ČR",
    kind: "budget-allocate",
    buildingName: "Spořící prasátko",
    buildingGlyph: "🐷",
    buildingRoof: "bg-pink-400",
    buildingBody: "bg-pink-600",
    source: "Česká bankovní asociace — dětské programy",
    notes: "Rozděl 300 Kč kapesného: potřeby / zábava / spoření.",
    angles: [
      "300 Kč týdenně: 50/30/20",
      "měsíční cíl 500 Kč — naspořím na prezent",
      "dětský účet vs prasátko",
      "co s 2000 Kč od babičky",
    ],
    age: "9-12",
    subject: "savings",
  },
  {
    theme: "Koruna vs euro — kdy Česko přijme euro",
    kind: "true-false",
    buildingName: "Eurozóna?",
    buildingGlyph: "💶",
    buildingRoof: "bg-blue-400",
    buildingBody: "bg-blue-600",
    source: "ČNB + ECB konvergenční kritéria",
    notes: "Maastrichtská kritéria, ERM II, historie.",
    angles: [
      "ČR musí vstoupit do eurozóny — pravda nebo zákon",
      "Maastrichtská inflační kritéria",
      "dvouleté ERM II",
      "referendum o euru",
    ],
    age: "16-19",
    subject: "everyday",
  },
  {
    theme: "Slevy na Černý pátek / Black Friday v ČR",
    kind: "what-if",
    buildingName: "Slevy",
    buildingGlyph: "🏷️",
    buildingRoof: "bg-rose-400",
    buildingBody: "bg-rose-700",
    source: "ČOI + dTest",
    notes: "Pravidlo 30 dní, fiktivní slevy.",
    angles: [
      "iPhone 'původní cena' 2 týdny vysoko, pak sleva",
      "jak poznat skutečnou slevu",
      "vratka do 14 dnů — online x kamenná prodejna",
      "reklamace vs odstoupení",
    ],
    age: "13-15",
    subject: "everyday",
  },
  {
    theme: "ČR minimální mzda 2026",
    kind: "fill-in-blank",
    buildingName: "Mzda",
    buildingGlyph: "💰",
    buildingRoof: "bg-emerald-400",
    buildingBody: "bg-emerald-600",
    source: "MPSV ČR",
    notes: "Minimální mzda, zaručená mzda, hodinové sazby.",
    angles: [
      "hrubá minimální mzda 2026 ___ Kč",
      "čistá minimální mzda ___ Kč",
      "zaručená mzda — 8 stupňů",
      "práce na DPP do ___ Kč měsíčně bez pojistného",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "České kryptoměny — regulace + MiCA",
    kind: "true-false",
    buildingName: "Crypto ČR",
    buildingGlyph: "🪙",
    buildingRoof: "bg-amber-500",
    buildingBody: "bg-amber-700",
    source: "MF ČR + EU MiCA",
    notes: "Jak funguje zdanění krypto v ČR 2026.",
    angles: [
      "MiCA licence pro CASP",
      "daňová povinnost při prodeji BTC",
      "tříletý test pro akcie — pro krypto neplatí",
      "VIES kontrola EU DPH",
    ],
    age: "16-19",
    subject: "investing",
  },
  {
    theme: "Invalidní, sirotčí, starobní důchod ČR",
    kind: "order",
    buildingName: "ČSSZ",
    buildingGlyph: "🏛️",
    buildingRoof: "bg-indigo-400",
    buildingBody: "bg-indigo-600",
    source: "ČSSZ + zákon o důchodovém pojištění",
    notes: "Seřaď důchody podle průměrné výše (od nejnižšího).",
    angles: [
      "sirotčí vs invalidní (2. stupeň) vs vdovský",
      "starobní vs předčasný důchod",
      "minimální pojistná doba",
      "valorizace 2026",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "Student v Praze — rozpočet 10 000 Kč",
    kind: "budget-allocate",
    buildingName: "Student",
    buildingGlyph: "🎓",
    buildingRoof: "bg-cyan-400",
    buildingBody: "bg-cyan-600",
    source: "Studentské fóra + CZSO",
    notes: "Kolej 4500, jídlo 2500, doprava 500, zábava 1000, rezerva 1500.",
    angles: [
      "kolej vs pronájem 2+kk se spolubydlícím",
      "jídelna Menza × jídlo doma",
      "ISIC / JUNIOR PASS",
      "stipendium — jak rozdělit",
    ],
    age: "16-19",
    subject: "budgeting",
  },
  {
    theme: "Česká pojišťovna vs Kooperativa — pojistné sazby",
    kind: "price-guess",
    buildingName: "Pojišťovna",
    buildingGlyph: "🛡️",
    buildingRoof: "bg-red-400",
    buildingBody: "bg-red-600",
    source: "ČAP + srovnávače 2026",
    notes: "Povinné ručení, KASKO, životní pojištění.",
    angles: [
      "POV pro Škoda Octavia / řidič 25 let",
      "havarijní pojištění 200 000 Kč auto",
      "životní pojištění 30 let člověk",
      "cestovní pojištění 2 týdny EU",
    ],
    age: "16-19",
    subject: "insurance",
  },
  {
    theme: "Refinancování hypotéky ČR 2026",
    kind: "calc-sprint",
    buildingName: "Refi",
    buildingGlyph: "🔄",
    buildingRoof: "bg-lime-400",
    buildingBody: "bg-lime-700",
    source: "Hypoteční srovnávače",
    notes: "Počítej úspory při refinancování.",
    angles: [
      "3 mil úvěr, 5 % → 3,5 % — měsíční rozdíl",
      "poplatek za refinancování 10 000 Kč — kdy se vyplatí",
      "zbývající 25 let → 20 let — rozdíl",
      "fixace nová 5Y — úvaha",
    ],
    age: "16-19",
    subject: "credit",
  },
  {
    theme: "MHD Praha vs jízda autem",
    kind: "chart-read",
    buildingName: "MHD",
    buildingGlyph: "🚋",
    buildingRoof: "bg-red-400",
    buildingBody: "bg-red-600",
    source: "DPP + české benzínky 2026",
    notes: "Graf porovnání nákladů MHD / auto / taxi.",
    angles: [
      "365denní kupón DPP vs benzín 15 000 km",
      "MHD + sdílení vs vlastní auto",
      "víkendová jízda mimo Prahu",
      "kolo + MHD — kombinace",
    ],
    age: "13-15",
    subject: "everyday",
  },
];

// ---------------------------------------------------------------------------
// UA market — 20 themes
// ---------------------------------------------------------------------------

export const UA_THEMES: Omit<ResearchSeed, "difficulty">[] = [
  {
    theme: "НБУ облікова ставка — вплив на гривню",
    kind: "quiz",
    buildingName: "НБУ Watch",
    buildingGlyph: "🏛️",
    buildingRoof: "bg-sky-400",
    buildingBody: "bg-sky-700",
    source: "НБУ + офіційні звіти",
    notes: "Як облікова ставка впливає на депозити, іпотеку, інфляцію.",
    angles: [
      "облікова ставка 15 % vs 20 % — наслідки",
      "депозити у грн vs у валюті",
      "інфляція 2026 — цільовий показник",
      "валютний коридор vs вільне плавання",
    ],
    age: "13-15",
    subject: "credit",
  },
  {
    theme: "ПриватБанк vs Monobank — банки України",
    kind: "match-pairs",
    buildingName: "Банк",
    buildingGlyph: "🏦",
    buildingRoof: "bg-green-400",
    buildingBody: "bg-green-700",
    source: "НБУ реєстр + банківська аналітика",
    notes: "Спаруй банк з його унікальною фішкою.",
    angles: [
      "Приват24 — класика; Monobank — мобільний",
      "Izi vs Ощадбанк — культура обслуговування",
      "корпоративний сегмент: Райфайзен, ПУМБ",
      "картки: Universal Card, Platinum, Black",
    ],
    age: "16-19",
    subject: "payments",
  },
  {
    theme: "ПДВ в Україні — 20 %, 7 %, 0 %",
    kind: "quiz",
    buildingName: "Податкова",
    buildingGlyph: "📜",
    buildingRoof: "bg-zinc-400",
    buildingBody: "bg-zinc-600",
    source: "Податковий кодекс України",
    notes: "Базова / знижена / нульова ставка — що до чого.",
    angles: [
      "книги, ліки — 7 %",
      "експорт — 0 %",
      "побутові послуги — 20 %",
      "реєстрація платника ПДВ з 1 000 000 грн",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "ПДФО + військовий збір — зарплата в УКР",
    kind: "fill-in-blank",
    buildingName: "Зарплата",
    buildingGlyph: "🧾",
    buildingRoof: "bg-amber-400",
    buildingBody: "bg-amber-700",
    source: "ДПС + військовий збір",
    notes: "18 % ПДФО + 5 % військовий збір — розрахуй чисту.",
    angles: [
      "20 000 грн брутто → чиста ___ грн",
      "ФОП 2 група — ставка ___",
      "ФОП 3 група + 5 % ЄП",
      "мінімалка 2026 — ___ грн",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "Перша квартира в Києві — оренда vs іпотека",
    kind: "what-if",
    buildingName: "Первый М",
    buildingGlyph: "🗝️",
    buildingRoof: "bg-fuchsia-400",
    buildingBody: "bg-fuchsia-600",
    source: "Ринок нерухомості Києва",
    notes: "Оренда 15 000 грн vs іпотека 1,5 млн грн.",
    angles: [
      "оренда 1-к Оболонь vs єОселя 7 %",
      "початковий внесок 15 %",
      "програма єОселя для ВПО",
      "вторинний vs первинний ринок",
    ],
    age: "16-19",
    subject: "realestate",
  },
  {
    theme: "Військові облігації України",
    kind: "quiz",
    buildingName: "Облігації",
    buildingGlyph: "📜",
    buildingRoof: "bg-yellow-400",
    buildingBody: "bg-yellow-700",
    source: "Мінфін + НБУ",
    notes: "ОВДП, дохідність, звільнення від ПДФО.",
    angles: [
      "мінімальна сума покупки",
      "звільнення від 18 % ПДФО",
      "дохідність 2026 — прогноз",
      "ризик дефолту держави",
    ],
    age: "16-19",
    subject: "investing",
  },
  {
    theme: "єПідтримка — державна допомога ВПО",
    kind: "true-false",
    buildingName: "Диія",
    buildingGlyph: "📱",
    buildingRoof: "bg-red-400",
    buildingBody: "bg-red-700",
    source: "Диія + Кабмін",
    notes: "Які програми доступні у 2026.",
    angles: [
      "єДопомога — хто отримує",
      "ВПО довідка — термін дії",
      "єКнига — учні 1-4 класу",
      "єОселя — програма іпотек",
    ],
    age: "16-19",
    subject: "everyday",
  },
  {
    theme: "Українська фондова біржа (УФБ, ПФТС)",
    kind: "scramble",
    buildingName: "Біржа",
    buildingGlyph: "📈",
    buildingRoof: "bg-blue-400",
    buildingBody: "bg-blue-700",
    source: "НКЦПФР",
    notes: "Терміни біржі українською.",
    angles: [
      "АКЦІЇ, ОБЛІГАЦІЇ, ДИВІДЕНДИ",
      "БРОКЕР, ТОРГИ, КОТИРУВАННЯ",
      "ВЕДМІДЬ, БИК, КОРЕКЦІЯ",
      "ДЕРИВАТИВ, ФЮЧЕРС, ОПЦІОН",
    ],
    age: "16-19",
    subject: "investing",
  },
  {
    theme: "ДТЕК і ціни на електроенергію",
    kind: "price-guess",
    buildingName: "ДТЕК",
    buildingGlyph: "⚡",
    buildingRoof: "bg-emerald-400",
    buildingBody: "bg-emerald-700",
    source: "НКРЕКП + ДТЕК",
    notes: "Ціни на електрику, дводобовий тариф, пільги.",
    angles: [
      "ціна 1 кВт·год для населення 2026",
      "розхід 2-к квартири за місяць",
      "тариф день/ніч — ефект",
      "сонячна панель 5 кВт — окупність",
    ],
    age: "13-15",
    subject: "energy",
  },
  {
    theme: "Пенсійна реформа в Україні",
    kind: "quiz",
    buildingName: "ПФУ",
    buildingGlyph: "👴",
    buildingRoof: "bg-violet-400",
    buildingBody: "bg-violet-600",
    source: "ПФУ + Мінсоцполітики",
    notes: "Стаж, мінімальна пенсія, трирівнева система.",
    angles: [
      "мінімальний стаж 2026",
      "рівень 1 / 2 / 3 — різниця",
      "накопичувальна пенсія — коли старт",
      "надбавка після 70 років",
    ],
    age: "16-19",
    subject: "investing",
  },
  {
    theme: "Кишенькові 200 грн на тиждень",
    kind: "budget-allocate",
    buildingName: "Кишеня",
    buildingGlyph: "🐷",
    buildingRoof: "bg-pink-400",
    buildingBody: "bg-pink-600",
    source: "ПриватБанк Junior",
    notes: "Розділи 200 грн на потреби / розваги / заощадження.",
    angles: [
      "200 грн/тиждень: 50/30/20",
      "ціль 1 000 грн — квест",
      "дитяча картка ПриватБанку",
      "подарунок 500 грн від діда",
    ],
    age: "9-12",
    subject: "savings",
  },
  {
    theme: "Гривня vs євро — перспектива",
    kind: "true-false",
    buildingName: "Курс",
    buildingGlyph: "💶",
    buildingRoof: "bg-blue-400",
    buildingBody: "bg-blue-600",
    source: "НБУ + МВФ",
    notes: "Як взаємодіють гривня, євро, долар.",
    angles: [
      "гривня фіксована до євро",
      "інтервенції НБУ",
      "валютний ринок — як працює",
      "заощадження у євро vs гривні",
    ],
    age: "16-19",
    subject: "everyday",
  },
  {
    theme: "Розпродажі в Україні — Чорна п'ятниця",
    kind: "what-if",
    buildingName: "Sale UA",
    buildingGlyph: "🏷️",
    buildingRoof: "bg-rose-400",
    buildingBody: "bg-rose-700",
    source: "Антимонопольний комітет",
    notes: "Фейкові ціни, правило 30 днів, захист споживача.",
    angles: [
      "Rozetka знижка 70 % — як перевірити",
      "гарантія vs повернення",
      "касовий чек — обов'язок продавця",
      "оплата частинами (ПриватБанк, Моно)",
    ],
    age: "13-15",
    subject: "everyday",
  },
  {
    theme: "Мінімальна зарплата України 2026",
    kind: "fill-in-blank",
    buildingName: "Мінімалка",
    buildingGlyph: "💰",
    buildingRoof: "bg-emerald-400",
    buildingBody: "bg-emerald-600",
    source: "Мінекономіки",
    notes: "Мінзарплата, прожитковий мінімум, ставки ЄСВ.",
    angles: [
      "мінзарплата 2026 ___ грн",
      "прожитковий мінімум ___ грн",
      "ЄСВ від мін. зарплати",
      "ФОП 2 гр. — ставка єдиного податку",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "Криптовалюта в Україні — закон 2022",
    kind: "true-false",
    buildingName: "Crypto UA",
    buildingGlyph: "🪙",
    buildingRoof: "bg-amber-500",
    buildingBody: "bg-amber-700",
    source: "Закон про віртуальні активи 2022",
    notes: "Легальний статус, оподаткування, НКЦПФР нагляд.",
    angles: [
      "крипто легалізована 2022",
      "ставка ПДФО при продажу",
      "реєстр провайдерів послуг",
      "MiCA vs український закон",
    ],
    age: "16-19",
    subject: "investing",
  },
  {
    theme: "Пенсія, стипендія, субсидія — соцвиплати",
    kind: "order",
    buildingName: "Соцфонд",
    buildingGlyph: "🏛️",
    buildingRoof: "bg-indigo-400",
    buildingBody: "bg-indigo-600",
    source: "ПФУ + Держстипендія + субсидія",
    notes: "Упорядкуй виплати за розміром (від найменшої).",
    angles: [
      "стипендія соціальна vs академічна",
      "пенсія мінімальна vs середня",
      "допомога по безробіттю",
      "субсидія на опалення",
    ],
    age: "16-19",
    subject: "taxes",
  },
  {
    theme: "Студент у Києві — бюджет 12 000 грн",
    kind: "budget-allocate",
    buildingName: "Студент UA",
    buildingGlyph: "🎓",
    buildingRoof: "bg-cyan-400",
    buildingBody: "bg-cyan-600",
    source: "Студентські спільноти Києва",
    notes: "Гуртожиток 2000 / їжа 4000 / транспорт 500 / розваги 2000 / резерв 3500.",
    angles: [
      "гуртожиток vs оренда зі спільнотою",
      "студентська їдальня vs доставка",
      "ISIC — знижки в УКР",
      "стипендія vs підробіток",
    ],
    age: "16-19",
    subject: "budgeting",
  },
  {
    theme: "ПЗУ України + Універсальна — страхові ставки",
    kind: "price-guess",
    buildingName: "Страхування",
    buildingGlyph: "🛡️",
    buildingRoof: "bg-red-400",
    buildingBody: "bg-red-600",
    source: "Нацкомфінпослуг + страхові 2026",
    notes: "ОСЦПВ, КАСКО, медичне, туристичне.",
    angles: [
      "ОСЦПВ для молодого водія в Києві",
      "КАСКО Toyota Corolla на рік",
      "медичне для дитини",
      "туристичне на 2 тижні ЄС",
    ],
    age: "16-19",
    subject: "insurance",
  },
  {
    theme: "Рефінансування іпотеки в УКР",
    kind: "calc-sprint",
    buildingName: "Refi UA",
    buildingGlyph: "🔄",
    buildingRoof: "bg-lime-400",
    buildingBody: "bg-lime-700",
    source: "Іпотечні калькулятори",
    notes: "Як підрахувати економію.",
    angles: [
      "1 млн грн, 15 % → 7 % (єОселя) — різниця платежу",
      "комісія 5 000 грн — період окупності",
      "залишок 20 років → 15",
      "фіксована vs плаваюча ставка",
    ],
    age: "16-19",
    subject: "credit",
  },
  {
    theme: "Громадський транспорт Києва vs авто",
    kind: "chart-read",
    buildingName: "Транспорт",
    buildingGlyph: "🚇",
    buildingRoof: "bg-red-400",
    buildingBody: "bg-red-600",
    source: "Київпастранс + бензин 2026",
    notes: "Графік порівняння витрат: метро / авто / таксі.",
    angles: [
      "проїзний на рік vs бензин 15 000 км",
      "Uber / Bolt vs власне авто",
      "Uklon PassSharing",
      "велосипед + метро",
    ],
    age: "13-15",
    subject: "everyday",
  },
];

// ---------------------------------------------------------------------------
// Landmarks per market — for future per-market CityScene overlays (9.1.3)
// ---------------------------------------------------------------------------

export type LandmarkDef = {
  id: string;
  labels: Record<string, string>;
  glyph: string;
};

export const LANDMARKS: Record<"pl" | "cz" | "ua", LandmarkDef[]> = {
  pl: [
    { id: "spodek", labels: { pl: "Spodek", en: "Spodek" }, glyph: "🛸" },
    { id: "varso", labels: { pl: "Varso Tower", en: "Varso Tower" }, glyph: "🗼" },
    { id: "pkin", labels: { pl: "Pałac Kultury", en: "Palace of Culture" }, glyph: "🏛️" },
  ],
  cz: [
    { id: "zizkov", labels: { cs: "Žižkovská věž", en: "Zizkov Tower" }, glyph: "🗼" },
    { id: "karluv-most", labels: { cs: "Karlův most", en: "Charles Bridge" }, glyph: "🌉" },
    { id: "narodni", labels: { cs: "Národní divadlo", en: "National Theatre" }, glyph: "🎭" },
    { id: "tancici-dum", labels: { cs: "Tančící dům", en: "Dancing House" }, glyph: "💃" },
  ],
  ua: [
    { id: "pecherska", labels: { uk: "Києво-Печерська лавра", en: "Lavra" }, glyph: "⛪" },
    { id: "khreshchatyk", labels: { uk: "Хрещатик", en: "Khreshchatyk" }, glyph: "🛣️" },
    { id: "batkivshchyna", labels: { uk: "Мати-Батьківщина", en: "Motherland Monument" }, glyph: "🗽" },
  ],
};
