#!/usr/bin/env tsx
/* W3 — generate ERC-721 metadata for every achievement in the catalog.
 *
 * Output: `lib/web3/medal-uris.ts`, a typed `Record<AchievementId, string>`
 * where the string is a `data:application/json;base64,…` URI whose
 * body embeds:
 *   - name (PL label)
 *   - description (PL description)
 *   - image (inline SVG rendering the emoji icon, base64-encoded)
 *   - attributes (achievementId, rarity, category)
 *
 * Data URIs mean the metadata is fully self-contained and works
 * without IPFS / any external host. Post-deploy, the operator can run
 * `scripts/upload-medal-metadata.ts` to re-host the same JSON on
 * NFT.Storage (the script overwrites medal-uris.ts with ipfs:// URIs).
 *
 * Usage:
 *   pnpm tsx scripts/build-medal-metadata.ts
 *
 * Idempotent — re-running produces byte-identical output given the
 * same ACHIEVEMENT_DEFS.
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { Buffer } from "node:buffer";
import { ACHIEVEMENT_DEFS, type AchievementId } from "../lib/achievements";

const CATEGORY: Record<AchievementId, string> = {
  "first-mortgage-paid": "finance",
  "evergreen-top3-sweep": "games",
  "ai-medals-10": "ai",
  "ai-medals-100": "ai",
  "built-t7": "city",
  "all-slots-filled": "city",
  "credit-score-100": "finance",
  "streak-30": "consistency",
};

const RARITY: Record<AchievementId, "common" | "rare" | "legendary"> = {
  "first-mortgage-paid": "common",
  "evergreen-top3-sweep": "legendary",
  "ai-medals-10": "rare",
  "ai-medals-100": "legendary",
  "built-t7": "rare",
  "all-slots-filled": "legendary",
  "credit-score-100": "rare",
  "streak-30": "rare",
};

function svgForIcon(icon: string, label: string): string {
  // Watt City brand: white bg, ink black border, accent stripe at top.
  // The icon is centered as a large emoji; the label fits in small caps
  // underneath. Viewport fixed at 512×512 for gallery consistency.
  const safeLabel = label.replace(/</g, "&lt;").replace(/>/g, "&gt;");
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512">
  <rect width="512" height="512" fill="#ffffff"/>
  <rect x="0" y="0" width="512" height="32" fill="#ffd81a"/>
  <rect x="0" y="32" width="512" height="460" fill="none" stroke="#000" stroke-width="6"/>
  <text x="256" y="280" font-size="220" text-anchor="middle" dominant-baseline="middle" font-family="system-ui, sans-serif">${icon}</text>
  <text x="256" y="440" font-size="22" text-anchor="middle" font-family="system-ui, sans-serif" fill="#000" font-weight="700" letter-spacing="2">WATT CITY MEDAL</text>
  <text x="256" y="470" font-size="16" text-anchor="middle" font-family="system-ui, sans-serif" fill="#555">${safeLabel}</text>
</svg>`;
}

function svgDataUri(svg: string): string {
  const b64 = Buffer.from(svg, "utf8").toString("base64");
  return `data:image/svg+xml;base64,${b64}`;
}

function jsonDataUri(obj: unknown): string {
  const b64 = Buffer.from(JSON.stringify(obj), "utf8").toString("base64");
  return `data:application/json;base64,${b64}`;
}

function buildMetadata(id: AchievementId) {
  const def = ACHIEVEMENT_DEFS[id];
  const image = svgDataUri(svgForIcon(def.icon, def.labels.pl));
  return {
    name: `Watt City · ${def.labels.pl}`,
    description: def.descriptions.pl,
    image,
    external_url: "https://watt-city.vercel.app",
    attributes: [
      { trait_type: "achievementId", value: id },
      { trait_type: "category", value: CATEGORY[id] },
      { trait_type: "rarity", value: RARITY[id] },
      { trait_type: "soulbound", value: "true" },
    ],
  };
}

function main() {
  const ids = Object.keys(ACHIEVEMENT_DEFS) as AchievementId[];
  const uris: Record<string, string> = {};
  for (const id of ids) {
    uris[id] = jsonDataUri(buildMetadata(id));
  }

  const tsBody = `/* AUTO-GENERATED by scripts/build-medal-metadata.ts — do not edit by hand.
 *
 * Maps every AchievementId to an ERC-721 metadata URI. Default output
 * is \`data:application/json;base64,…\` so the tokenURI is fully
 * self-contained (no IPFS dep). To move to IPFS, run:
 *   pnpm tsx scripts/upload-medal-metadata.ts
 * which replaces every entry with an \`ipfs://<cid>\` URI after pinning
 * the JSON via NFT.Storage.
 *
 * The map is exhaustive — the vitest guard
 * \`lib/web3/medal-uris.test.ts\` fails CI if a new AchievementId
 * lands in lib/achievements.ts without a corresponding entry here.
 */

import type { AchievementId } from "@/lib/achievements";

export const MEDAL_URIS: Record<AchievementId, string> = ${JSON.stringify(
    uris,
    null,
    2,
  )};
`;

  const outPath = join(process.cwd(), "lib/web3/medal-uris.ts");
  writeFileSync(outPath, tsBody);
  console.log(`Wrote ${ids.length} medal URIs to lib/web3/medal-uris.ts`);
  for (const id of ids) {
    console.log(`  ${id}: ${uris[id].length} bytes`);
  }
}

main();
