#!/usr/bin/env tsx
/* W3 (optional) — re-host medal metadata on IPFS via NFT.Storage.
 *
 * Reads the current MEDAL_URIS (data URIs from build-medal-metadata.ts),
 * re-decodes the JSON, uploads it to NFT.Storage, and rewrites
 * lib/web3/medal-uris.ts with ipfs:// CIDs.
 *
 * Why this is opt-in: data URIs already work for the contract's
 * tokenURI() — a wallet or block explorer decodes them just fine.
 * IPFS pinning is a nice-to-have (offloads bytes from the chain) that
 * requires an operator-provided NFT_STORAGE_API_KEY. Running without
 * the key is a no-op that exits 0 with a warning, so CI pipelines
 * can call the script unconditionally.
 *
 * Usage:
 *   NFT_STORAGE_API_KEY=... pnpm tsx scripts/upload-medal-metadata.ts
 *
 * Rate-limit handling: 1 s sleep between uploads.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { Buffer } from "node:buffer";

const ROOT = join(__dirname, "..");
const URIS_PATH = join(ROOT, "lib/web3/medal-uris.ts");

function readDataUrisMap(): Record<string, string> {
  const src = readFileSync(URIS_PATH, "utf8");
  const match = src.match(
    /MEDAL_URIS:\s*Record<AchievementId,\s*string>\s*=\s*(\{[\s\S]+?\});/,
  );
  if (!match) {
    throw new Error("Could not parse MEDAL_URIS object from medal-uris.ts");
  }
  // Intentionally tight eval — the file is machine-generated by
  // build-medal-metadata.ts, so the shape is well-known and trusted.
  // eslint-disable-next-line no-new-func
  return new Function(`return (${match[1]});`)() as Record<string, string>;
}

function decodeDataUri(uri: string): unknown {
  const prefix = "data:application/json;base64,";
  if (!uri.startsWith(prefix)) {
    throw new Error(`Expected base64 JSON data URI; got: ${uri.slice(0, 60)}`);
  }
  const b64 = uri.slice(prefix.length);
  return JSON.parse(Buffer.from(b64, "base64").toString("utf8"));
}

async function pinJson(
  apiKey: string,
  payload: unknown,
): Promise<string /* ipfs://<cid> */> {
  // NFT.Storage API v1: POST /upload with JSON body.
  // Docs: https://nft.storage/api-docs
  const res = await fetch("https://api.nft.storage/upload", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(payload),
  });
  if (!res.ok) {
    throw new Error(`NFT.Storage upload failed: ${res.status} ${await res.text()}`);
  }
  const j = (await res.json()) as { ok: boolean; value?: { cid: string } };
  if (!j.ok || !j.value?.cid) {
    throw new Error(`NFT.Storage response malformed: ${JSON.stringify(j)}`);
  }
  return `ipfs://${j.value.cid}`;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function main() {
  const apiKey = process.env.NFT_STORAGE_API_KEY;
  if (!apiKey) {
    console.warn(
      "NFT_STORAGE_API_KEY not set — skipping IPFS re-host. Data URIs stay in place.",
    );
    return;
  }

  const current = readDataUrisMap();
  const next: Record<string, string> = {};
  for (const [id, uri] of Object.entries(current)) {
    if (uri.startsWith("ipfs://")) {
      next[id] = uri;
      console.log(`skip ${id}: already on IPFS (${uri})`);
      continue;
    }
    const payload = decodeDataUri(uri);
    const cid = await pinJson(apiKey, payload);
    next[id] = cid;
    console.log(`pinned ${id}: ${cid}`);
    await sleep(1000);
  }

  const src = readFileSync(URIS_PATH, "utf8");
  const rewritten = src.replace(
    /MEDAL_URIS:\s*Record<AchievementId,\s*string>\s*=\s*\{[\s\S]+?\};/,
    `MEDAL_URIS: Record<AchievementId, string> = ${JSON.stringify(
      next,
      null,
      2,
    )};`,
  );
  writeFileSync(URIS_PATH, rewritten);
  console.log(`\n✅ Rewrote lib/web3/medal-uris.ts with ${Object.keys(next).length} IPFS URIs.`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
